// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taskify.Tasks.Api.Data;

#nullable disable

namespace Taskify.Tasks.Api.Data.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20261004171255_AddComments")]
    partial class AddComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taskify.Security.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasFilter("\"DispatchedAt\" IS NULL AND \"DeadLetteredAt\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Taskify.Tasks.Api.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "CreatedAt");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Taskify.Tasks.Api.Domain.StatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("MovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "MovedAt")
                        .IsDescending(false, true);

                    b.ToTable("status_changes", (string)null);
                });

            modelBuilder.Entity("Taskify.Tasks.Api.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000001"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "Done",
                            Title = "Set up CI for iOS builds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000002"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "Done",
                            Title = "Design app icon",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "Done",
                            Title = "Create release checklist",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000004"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "InProgress",
                            Title = "Implement push notifications",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000005"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "InProgress",
                            Title = "Build offline mode",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000006"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "InReview",
                            Title = "Login screen accessibility fixes",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000007"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "InReview",
                            Title = "Onboarding copy review",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000008"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "ToDo",
                            Title = "Write App Store description",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "ToDo",
                            Title = "Plan beta tester outreach",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0001-000000000010"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000001"),
                            Status = "ToDo",
                            Title = "Define crash reporting thresholds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000001"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "Done",
                            Title = "Choose design system",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000002"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "Done",
                            Title = "Set up staging site",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000003"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "Done",
                            Title = "Redirect map for old URLs",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000004"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "InProgress",
                            Title = "Implement responsive navigation",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000005"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "InProgress",
                            Title = "Migrate blog to new layout",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 16, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000006"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "InReview",
                            Title = "Homepage hero section",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "InReview",
                            Title = "Cookie banner wording",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000008"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "ToDo",
                            Title = "Audit current page speed",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "ToDo",
                            Title = "Collect customer testimonials",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0002-000000000010"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000002"),
                            Status = "ToDo",
                            Title = "Draft new pricing page",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000001"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "Done",
                            Title = "Set up team chat channels",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000002"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "Done",
                            Title = "Inventory of software licenses",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "Done",
                            Title = "Create IT help page",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000004"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "InProgress",
                            Title = "Build team calendar integration",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000005"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "InProgress",
                            Title = "Clean up shared drive",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000006"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "InReview",
                            Title = "Expense report template",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "InReview",
                            Title = "Access request process",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "ToDo",
                            Title = "Evaluate time-tracking tools",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000009"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "ToDo",
                            Title = "Write onboarding guide for new hires",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-0003-000000000010"),
                            AssigneeUserId = new Guid("11111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-000000000001"),
                            ProjectId = new Guid("22222222-2222-2222-2222-000000000003"),
                            Status = "ToDo",
                            Title = "Automate weekly status report",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Taskify.Tasks.Api.Domain.Comment", b =>
                {
                    b.HasOne("Taskify.Tasks.Api.Domain.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskify.Tasks.Api.Domain.StatusChange", b =>
                {
                    b.HasOne("Taskify.Tasks.Api.Domain.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
