<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Taskify.Contracts\Taskify.Contracts.csproj" />
    <ProjectReference Include="..\Taskify.TestSupport\Taskify.TestSupport.csproj" />
  </ItemGroup>

</Project>
